fof(t56_filter_1,conjecture,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v3_filter_0(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( r3_lattices(A,k4_filter_0(A,B,C),k4_filter_0(A,B,k3_lattices(A,C,D)))& r3_lattices(A,k4_filter_0(A,B,C),k4_filter_0(A,k4_lattices(A,B,D),C))& r3_lattices(A,k4_filter_0(A,B,C),k4_filter_0(A,B,k3_lattices(A,D,C)))& r3_lattices(A,k4_filter_0(A,B,C),k4_filter_0(A,k4_lattices(A,D,B),C)) ) ) ) ) ) )).
fof(t25_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v5_lattices(A)& l2_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( ( r1_lattices(A,B,C)& r1_lattices(A,C,D) )=> r1_lattices(A,B,D) ) ) ) ) ) )).
fof(t23_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v6_lattices(A)& v8_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> r1_lattices(A,k4_lattices(A,B,C),B) ) ) ) )).
fof(d8_filter_0,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ( ( ~ v2_struct_0(A)& v10_lattices(A)& v3_filter_0(A)& l3_lattices(A) )=> ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( D = k4_filter_0(A,B,C)<=> ( r3_lattices(A,k4_lattices(A,B,D),C)& ! [E] :( m1_subset_1(E,u1_struct_0(A))=> ( r3_lattices(A,k4_lattices(A,B,E),C)=> r3_lattices(A,E,D) ) ) ) ) ) ) ) ) ) )).
fof(dt_k3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v4_lattices(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k3_lattices(A,B,C),u1_struct_0(A)) ) )).
fof(t27_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v7_lattices(A)& v8_lattices(A)& v9_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( r1_lattices(A,B,C)=> r1_lattices(A,k2_lattices(A,B,D),k2_lattices(A,C,D)) ) ) ) ) ) )).
fof(dt_l3_lattices,axiom,(! [A] :( l3_lattices(A)=> ( l1_lattices(A)& l2_lattices(A) ) ) )).
fof(redefinition_r3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& v8_lattices(A)& v9_lattices(A)& l3_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> ( r3_lattices(A,B,C)<=> r1_lattices(A,B,C) ) ) )).
fof(cc1_lattices,axiom,(! [A] :( l3_lattices(A)=> ( ( ~ v2_struct_0(A)& v10_lattices(A) )=> ( ~ v2_struct_0(A)& v4_lattices(A)& v5_lattices(A)& v6_lattices(A)& v7_lattices(A)& v8_lattices(A)& v9_lattices(A) ) ) ) )).
fof(commutativity_k3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v4_lattices(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k3_lattices(A,B,C) = k3_lattices(A,C,B) ) )).
fof(dt_k4_filter_0,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v10_lattices(A)& l3_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k4_filter_0(A,B,C),u1_struct_0(A)) ) )).
fof(commutativity_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k4_lattices(A,B,C) = k4_lattices(A,C,B) ) )).
fof(redefinition_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k4_lattices(A,B,C) = k2_lattices(A,B,C) ) )).
fof(t22_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v5_lattices(A)& v6_lattices(A)& v8_lattices(A)& v9_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> r1_lattices(A,B,k1_lattices(A,B,C)) ) ) ) )).
fof(redefinition_k3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v4_lattices(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k3_lattices(A,B,C) = k1_lattices(A,B,C) ) )).
fof(dt_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k4_lattices(A,B,C),u1_struct_0(A)) ) )).
