fof(t52_filter_1,conjecture,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ( k7_lattices(A,k4_filter_0(A,B,C)) = k4_lattices(A,B,k7_lattices(A,C))& k7_lattices(A,k7_filter_0(A,B,C)) = k3_lattices(A,k4_lattices(A,B,k7_lattices(A,C)),k4_lattices(A,k7_lattices(A,B),C))& k7_lattices(A,k7_filter_0(A,B,C)) = k7_filter_0(A,B,k7_lattices(A,C))& k7_lattices(A,k7_filter_0(A,B,C)) = k7_filter_0(A,k7_lattices(A,B),C) ) ) ) ) )).
fof(t49_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> k7_lattices(A,k7_lattices(A,B)) = B ) ) )).
fof(d11_filter_0,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> k7_filter_0(A,B,C) = k4_lattices(A,k4_filter_0(A,B,C),k4_filter_0(A,C,B)) ) ) ) )).
fof(dt_u2_lattices,axiom,(! [A] :( l2_lattices(A)=> ( v1_funct_1(u2_lattices(A))& v1_funct_2(u2_lattices(A),k2_zfmisc_1(u1_struct_0(A),u1_struct_0(A)),u1_struct_0(A))& m1_subset_1(u2_lattices(A),k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(u1_struct_0(A),u1_struct_0(A)),u1_struct_0(A)))) ) ) )).
fof(commutativity_k3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v4_lattices(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k3_lattices(A,B,C) = k3_lattices(A,C,B) ) )).
fof(existence_m1_subset_1,axiom,(! [A] :? [B] : m1_subset_1(B,A) )).
fof(dt_k4_binop_1,axiom,(! [A,B,C,D] :( ( v1_funct_1(B)& v1_funct_2(B,k2_zfmisc_1(A,A),A)& m1_subset_1(B,k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(A,A),A)))& m1_subset_1(C,A)& m1_subset_1(D,A) )=> m1_subset_1(k4_binop_1(A,B,C,D),A) ) )).
fof(t51_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> k7_lattices(A,k3_lattices(A,B,C)) = k4_lattices(A,k7_lattices(A,B),k7_lattices(A,C)) ) ) ) )).
fof(dt_k4_filter_0,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v10_lattices(A)& l3_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k4_filter_0(A,B,C),u1_struct_0(A)) ) )).
fof(dt_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k4_lattices(A,B,C),u1_struct_0(A)) ) )).
fof(dt_k2_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k2_lattices(A,B,C),u1_struct_0(A)) ) )).
fof(t51_filter_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> k7_filter_0(A,B,C) = k3_lattices(A,k4_lattices(A,B,C),k4_lattices(A,k7_lattices(A,B),k7_lattices(A,C))) ) ) ) )).
fof(dt_l3_lattices,axiom,(! [A] :( l3_lattices(A)=> ( l1_lattices(A)& l2_lattices(A) ) ) )).
fof(cc1_lattices,axiom,(! [A] :( l3_lattices(A)=> ( ( ~ v2_struct_0(A)& v10_lattices(A) )=> ( ~ v2_struct_0(A)& v4_lattices(A)& v5_lattices(A)& v6_lattices(A)& v7_lattices(A)& v8_lattices(A)& v9_lattices(A) ) ) ) )).
fof(dt_u1_lattices,axiom,(! [A] :( l1_lattices(A)=> ( v1_funct_1(u1_lattices(A))& v1_funct_2(u1_lattices(A),k2_zfmisc_1(u1_struct_0(A),u1_struct_0(A)),u1_struct_0(A))& m1_subset_1(u1_lattices(A),k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(u1_struct_0(A),u1_struct_0(A)),u1_struct_0(A)))) ) ) )).
fof(commutativity_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k4_lattices(A,B,C) = k4_lattices(A,C,B) ) )).
fof(t50_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> k7_lattices(A,k4_lattices(A,B,C)) = k3_lattices(A,k7_lattices(A,B),k7_lattices(A,C)) ) ) ) )).
fof(t55_filter_0,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> k4_filter_0(A,B,C) = k3_lattices(A,k7_lattices(A,B),C) ) ) ) )).
fof(redefinition_k4_binop_1,axiom,(! [A,B,C,D] :( ( v1_funct_1(B)& v1_funct_2(B,k2_zfmisc_1(A,A),A)& m1_subset_1(B,k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(A,A),A)))& m1_subset_1(C,A)& m1_subset_1(D,A) )=> k4_binop_1(A,B,C,D) = k1_binop_1(B,C,D) ) )).
fof(dt_k7_filter_0,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v10_lattices(A)& l3_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k7_filter_0(A,B,C),u1_struct_0(A)) ) )).
fof(dt_k7_lattices,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& l3_lattices(A)& m1_subset_1(B,u1_struct_0(A)) )=> m1_subset_1(k7_lattices(A,B),u1_struct_0(A)) ) )).
fof(dt_k3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v4_lattices(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k3_lattices(A,B,C),u1_struct_0(A)) ) )).
fof(dt_k1_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k1_lattices(A,B,C),u1_struct_0(A)) ) )).
fof(existence_l3_lattices,axiom,(? [A] : l3_lattices(A) )).
