fof(t52_lattices,conjecture,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ( k4_lattices(A,B,C) = k5_lattices(A)<=> r3_lattices(A,B,k7_lattices(A,C)) ) ) ) ) )).
fof(t26_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v4_lattices(A)& l2_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ( ( r1_lattices(A,B,C)& r1_lattices(A,C,B) )=> B = C ) ) ) ) )).
fof(t43_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v14_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> k4_lattices(A,k6_lattices(A),B) = B ) ) )).
fof(t47_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> k4_lattices(A,k7_lattices(A,B),B) = k5_lattices(A) ) ) )).
fof(commutativity_k3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v4_lattices(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k3_lattices(A,B,C) = k3_lattices(A,C,B) ) )).
fof(redefinition_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k4_lattices(A,B,C) = k2_lattices(A,B,C) ) )).
fof(cc4_lattices,axiom,(! [A] :( l3_lattices(A)=> ( ( ~ v2_struct_0(A)& v15_lattices(A) )=> ( ~ v2_struct_0(A)& v13_lattices(A)& v14_lattices(A) ) ) ) )).
fof(dt_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k4_lattices(A,B,C),u1_struct_0(A)) ) )).
fof(dt_k2_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k2_lattices(A,B,C),u1_struct_0(A)) ) )).
fof(t27_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v7_lattices(A)& v8_lattices(A)& v9_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( r1_lattices(A,B,C)=> r1_lattices(A,k2_lattices(A,B,D),k2_lattices(A,C,D)) ) ) ) ) ) )).
fof(d11_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& l3_lattices(A) )=> ( v11_lattices(A)<=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ! [D] :( m1_subset_1(D,u1_struct_0(A))=> k2_lattices(A,B,k1_lattices(A,C,D)) = k1_lattices(A,k2_lattices(A,B,C),k2_lattices(A,B,D)) ) ) ) ) ) )).
fof(dt_l3_lattices,axiom,(! [A] :( l3_lattices(A)=> ( l1_lattices(A)& l2_lattices(A) ) ) )).
fof(redefinition_r3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& v8_lattices(A)& v9_lattices(A)& l3_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> ( r3_lattices(A,B,C)<=> r1_lattices(A,B,C) ) ) )).
fof(cc1_lattices,axiom,(! [A] :( l3_lattices(A)=> ( ( ~ v2_struct_0(A)& v10_lattices(A) )=> ( ~ v2_struct_0(A)& v4_lattices(A)& v5_lattices(A)& v6_lattices(A)& v7_lattices(A)& v8_lattices(A)& v9_lattices(A) ) ) ) )).
fof(commutativity_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k4_lattices(A,B,C) = k4_lattices(A,C,B) ) )).
fof(d3_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& l2_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ( r1_lattices(A,B,C)<=> k1_lattices(A,B,C) = C ) ) ) ) )).
fof(t41_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v13_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> r3_lattices(A,k5_lattices(A),B) ) ) )).
fof(d8_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& l3_lattices(A) )=> ( v8_lattices(A)<=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> k1_lattices(A,k2_lattices(A,B,C),C) = C ) ) ) ) )).
fof(cc5_lattices,axiom,(! [A] :( l3_lattices(A)=> ( ( ~ v2_struct_0(A)& v17_lattices(A) )=> ( ~ v2_struct_0(A)& v11_lattices(A)& v15_lattices(A)& v16_lattices(A) ) ) ) )).
fof(dt_k7_lattices,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& l3_lattices(A)& m1_subset_1(B,u1_struct_0(A)) )=> m1_subset_1(k7_lattices(A,B),u1_struct_0(A)) ) )).
fof(t39_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v13_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> k3_lattices(A,k5_lattices(A),B) = B ) ) )).
fof(dt_k1_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k1_lattices(A,B,C),u1_struct_0(A)) ) )).
fof(t48_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> k3_lattices(A,k7_lattices(A,B),B) = k6_lattices(A) ) ) )).
fof(redefinition_k3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v4_lattices(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k3_lattices(A,B,C) = k1_lattices(A,B,C) ) )).
