fof(t32_lattices,conjecture,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v11_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( ( k4_lattices(A,B,C) = k4_lattices(A,B,D)& k3_lattices(A,B,C) = k3_lattices(A,B,D) )=> C = D ) ) ) ) ) )).
fof(dt_k2_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k2_lattices(A,B,C),u1_struct_0(A)) ) )).
fof(dt_k3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v4_lattices(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k3_lattices(A,B,C),u1_struct_0(A)) ) )).
fof(d9_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& l3_lattices(A) )=> ( v9_lattices(A)<=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> k2_lattices(A,B,k1_lattices(A,B,C)) = B ) ) ) ) )).
fof(d11_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& l3_lattices(A) )=> ( v11_lattices(A)<=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ! [D] :( m1_subset_1(D,u1_struct_0(A))=> k2_lattices(A,B,k1_lattices(A,C,D)) = k1_lattices(A,k2_lattices(A,B,C),k2_lattices(A,B,D)) ) ) ) ) ) )).
fof(dt_l3_lattices,axiom,(! [A] :( l3_lattices(A)=> ( l1_lattices(A)& l2_lattices(A) ) ) )).
fof(cc1_lattices,axiom,(! [A] :( l3_lattices(A)=> ( ( ~ v2_struct_0(A)& v10_lattices(A) )=> ( ~ v2_struct_0(A)& v4_lattices(A)& v5_lattices(A)& v6_lattices(A)& v7_lattices(A)& v8_lattices(A)& v9_lattices(A) ) ) ) )).
fof(commutativity_k3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v4_lattices(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k3_lattices(A,B,C) = k3_lattices(A,C,B) ) )).
fof(redefinition_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k4_lattices(A,B,C) = k2_lattices(A,B,C) ) )).
fof(commutativity_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k4_lattices(A,B,C) = k4_lattices(A,C,B) ) )).
fof(redefinition_k3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v4_lattices(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k3_lattices(A,B,C) = k1_lattices(A,B,C) ) )).
fof(dt_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k4_lattices(A,B,C),u1_struct_0(A)) ) )).
