fof(t35_tmap_1,conjecture,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& m1_pre_topc(B,A) )=> ! [C] :( ( ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> ! [D] :( ( ~ v2_struct_0(D)& m1_pre_topc(D,A) )=> ! [E] :( ( ~ v2_struct_0(E)& m1_pre_topc(E,A) )=> ( ( m1_pre_topc(B,C)& m1_pre_topc(D,E) )=> ( ( ~ r1_tsep_1(C,E)& ~ r1_tsep_1(k2_tsep_1(A,C,E),k1_tsep_1(A,B,D)) )| ( r1_tsep_1(C,D)& r1_tsep_1(E,B) ) ) ) ) ) ) ) ) )).
fof(dt_k2_tsep_1,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& l1_pre_topc(A)& ~ v2_struct_0(B)& m1_pre_topc(B,A)& ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> ( ~ v2_struct_0(k2_tsep_1(A,B,C))& v1_pre_topc(k2_tsep_1(A,B,C))& m1_pre_topc(k2_tsep_1(A,B,C),A) ) ) )).
fof(symmetry_r1_tsep_1,axiom,(! [A,B] :( ( l1_struct_0(A)& l1_struct_0(B) )=> ( r1_tsep_1(A,B)=> r1_tsep_1(B,A) ) ) )).
fof(commutativity_k1_tsep_1,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& l1_pre_topc(A)& ~ v2_struct_0(B)& m1_pre_topc(B,A)& ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> k1_tsep_1(A,B,C) = k1_tsep_1(A,C,B) ) )).
fof(dt_l1_pre_topc,axiom,(! [A] :( l1_pre_topc(A)=> l1_struct_0(A) ) )).
fof(dt_m1_pre_topc,axiom,(! [A] :( l1_pre_topc(A)=> ! [B] :( m1_pre_topc(B,A)=> l1_pre_topc(B) ) ) )).
fof(existence_l1_pre_topc,axiom,(? [A] : l1_pre_topc(A) )).
fof(dt_k1_tsep_1,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& l1_pre_topc(A)& ~ v2_struct_0(B)& m1_pre_topc(B,A)& ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> ( ~ v2_struct_0(k1_tsep_1(A,B,C))& v1_pre_topc(k1_tsep_1(A,B,C))& m1_pre_topc(k1_tsep_1(A,B,C),A) ) ) )).
fof(t34_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& m1_pre_topc(B,A) )=> ! [C] :( ( ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> ! [D] :( ( ~ v2_struct_0(D)& m1_pre_topc(D,A) )=> ( ~ r1_tsep_1(B,C)=> ( ( m1_pre_topc(B,D)=> ( ~ r1_tsep_1(k2_tsep_1(A,D,C),B)& ~ r1_tsep_1(k2_tsep_1(A,C,D),B) ) )& ( m1_pre_topc(C,D)=> ( ~ r1_tsep_1(k2_tsep_1(A,B,D),C)& ~ r1_tsep_1(k2_tsep_1(A,D,B),C) ) ) ) ) ) ) ) ) )).
fof(t23_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& m1_pre_topc(B,A) )=> ! [C] :( ( ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> ! [D] :( ( ~ v2_struct_0(D)& m1_pre_topc(D,A) )=> ( m1_pre_topc(B,C)=> ( ( r1_tsep_1(B,D)& r1_tsep_1(D,B) )| ( ~ r1_tsep_1(C,D)& ~ r1_tsep_1(D,C) ) ) ) ) ) ) ) )).
fof(existence_m1_pre_topc,axiom,(! [A] :( l1_pre_topc(A)=> ? [B] : m1_pre_topc(B,A) ) )).
fof(t22_tsep_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& m1_pre_topc(B,A) )=> ! [C] :( ( ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> m1_pre_topc(B,k1_tsep_1(A,B,C)) ) ) ) )).
