fof(t140_tmap_1,conjecture,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& v2_pre_topc(B)& l1_pre_topc(B) )=> ! [C] :( ( ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> ! [D] :( ( ~ v2_struct_0(D)& m1_pre_topc(D,A) )=> ( ~ r1_tsep_1(C,D)=> ! [E] :( ( v1_funct_1(E)& v1_funct_2(E,u1_struct_0(C),u1_struct_0(B))& m1_subset_1(E,k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(C),u1_struct_0(B)))) )=> ! [F] :( ( v1_funct_1(F)& v1_funct_2(F,u1_struct_0(D),u1_struct_0(B))& m1_subset_1(F,k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(D),u1_struct_0(B)))) )=> ( ( r2_funct_2(u1_struct_0(C),u1_struct_0(B),k3_tmap_1(A,B,k1_tsep_1(A,C,D),C,k10_tmap_1(A,B,C,D,E,F)),E)& r2_funct_2(u1_struct_0(D),u1_struct_0(B),k3_tmap_1(A,B,k1_tsep_1(A,C,D),D,k10_tmap_1(A,B,C,D,E,F)),F) )<=> r2_funct_2(u1_struct_0(k2_tsep_1(A,C,D)),u1_struct_0(B),k3_tmap_1(A,B,C,k2_tsep_1(A,C,D),E),k3_tmap_1(A,B,D,k2_tsep_1(A,C,D),F)) ) ) ) ) ) ) ) ) )).
fof(dt_k3_tmap_1,axiom,(! [A,B,C,D,E] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A)& ~ v2_struct_0(B)& v2_pre_topc(B)& l1_pre_topc(B)& m1_pre_topc(C,A)& m1_pre_topc(D,A)& v1_funct_1(E)& v1_funct_2(E,u1_struct_0(C),u1_struct_0(B))& m1_subset_1(E,k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(C),u1_struct_0(B)))) )=> ( v1_funct_1(k3_tmap_1(A,B,C,D,E))& v1_funct_2(k3_tmap_1(A,B,C,D,E),u1_struct_0(D),u1_struct_0(B))& m1_subset_1(k3_tmap_1(A,B,C,D,E),k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(D),u1_struct_0(B)))) ) ) )).
fof(redefinition_r2_funct_2,axiom,(! [A,B,C,D] :( ( v1_funct_1(C)& v1_funct_2(C,A,B)& m1_subset_1(C,k1_zfmisc_1(k2_zfmisc_1(A,B)))& v1_funct_1(D)& v1_funct_2(D,A,B)& m1_subset_1(D,k1_zfmisc_1(k2_zfmisc_1(A,B))) )=> ( r2_funct_2(A,B,C,D)<=> C = D ) ) )).
fof(dt_k10_tmap_1,axiom,(! [A,B,C,D,E,F] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A)& ~ v2_struct_0(B)& v2_pre_topc(B)& l1_pre_topc(B)& ~ v2_struct_0(C)& m1_pre_topc(C,A)& ~ v2_struct_0(D)& m1_pre_topc(D,A)& v1_funct_1(E)& v1_funct_2(E,u1_struct_0(C),u1_struct_0(B))& m1_subset_1(E,k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(C),u1_struct_0(B))))& v1_funct_1(F)& v1_funct_2(F,u1_struct_0(D),u1_struct_0(B))& m1_subset_1(F,k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(D),u1_struct_0(B)))) )=> ( v1_funct_1(k10_tmap_1(A,B,C,D,E,F))& v1_funct_2(k10_tmap_1(A,B,C,D,E,F),u1_struct_0(k1_tsep_1(A,C,D)),u1_struct_0(B))& m1_subset_1(k10_tmap_1(A,B,C,D,E,F),k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(k1_tsep_1(A,C,D)),u1_struct_0(B)))) ) ) )).
fof(d13_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& v2_pre_topc(B)& l1_pre_topc(B) )=> ! [C] :( ( ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> ! [D] :( ( ~ v2_struct_0(D)& m1_pre_topc(D,A) )=> ! [E] :( ( v1_funct_1(E)& v1_funct_2(E,u1_struct_0(C),u1_struct_0(B))& m1_subset_1(E,k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(C),u1_struct_0(B)))) )=> ! [F] :( ( v1_funct_1(F)& v1_funct_2(F,u1_struct_0(D),u1_struct_0(B))& m1_subset_1(F,k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(D),u1_struct_0(B)))) )=> ( ( r1_tsep_1(C,D)| r2_funct_2(u1_struct_0(k2_tsep_1(A,C,D)),u1_struct_0(B),k3_tmap_1(A,B,C,k2_tsep_1(A,C,D),E),k3_tmap_1(A,B,D,k2_tsep_1(A,C,D),F)) )=> ! [G] :( ( v1_funct_1(G)& v1_funct_2(G,u1_struct_0(k1_tsep_1(A,C,D)),u1_struct_0(B))& m1_subset_1(G,k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(k1_tsep_1(A,C,D)),u1_struct_0(B)))) )=> ( G = k10_tmap_1(A,B,C,D,E,F)<=> ( r2_funct_2(u1_struct_0(C),u1_struct_0(B),k3_tmap_1(A,B,k1_tsep_1(A,C,D),C,G),E)& r2_funct_2(u1_struct_0(D),u1_struct_0(B),k3_tmap_1(A,B,k1_tsep_1(A,C,D),D,G),F) ) ) ) ) ) ) ) ) ) ) )).
fof(t30_tsep_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& m1_pre_topc(B,A) )=> ! [C] :( ( ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> ( ~ r1_tsep_1(B,C)=> ( m1_pre_topc(k2_tsep_1(A,B,C),B)& m1_pre_topc(k2_tsep_1(A,B,C),C) ) ) ) ) ) )).
fof(dt_k2_tsep_1,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& l1_pre_topc(A)& ~ v2_struct_0(B)& m1_pre_topc(B,A)& ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> ( ~ v2_struct_0(k2_tsep_1(A,B,C))& v1_pre_topc(k2_tsep_1(A,B,C))& m1_pre_topc(k2_tsep_1(A,B,C),A) ) ) )).
fof(t79_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& v2_pre_topc(B)& l1_pre_topc(B) )=> ! [C] :( ( ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> ! [D] :( ( ~ v2_struct_0(D)& m1_pre_topc(D,A) )=> ! [E] :( ( ~ v2_struct_0(E)& m1_pre_topc(E,A) )=> ( ( m1_pre_topc(D,C)& m1_pre_topc(E,D) )=> ! [F] :( ( v1_funct_1(F)& v1_funct_2(F,u1_struct_0(C),u1_struct_0(B))& m1_subset_1(F,k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(C),u1_struct_0(B)))) )=> r2_funct_2(u1_struct_0(E),u1_struct_0(B),k3_tmap_1(A,B,D,E,k3_tmap_1(A,B,C,D,F)),k3_tmap_1(A,B,C,E,F)) ) ) ) ) ) ) ) )).
fof(dt_m1_pre_topc,axiom,(! [A] :( l1_pre_topc(A)=> ! [B] :( m1_pre_topc(B,A)=> l1_pre_topc(B) ) ) )).
fof(dt_k1_tsep_1,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& l1_pre_topc(A)& ~ v2_struct_0(B)& m1_pre_topc(B,A)& ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> ( ~ v2_struct_0(k1_tsep_1(A,B,C))& v1_pre_topc(k1_tsep_1(A,B,C))& m1_pre_topc(k1_tsep_1(A,B,C),A) ) ) )).
fof(t22_tsep_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& m1_pre_topc(B,A) )=> ! [C] :( ( ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> m1_pre_topc(B,k1_tsep_1(A,B,C)) ) ) ) )).
fof(commutativity_k1_tsep_1,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& l1_pre_topc(A)& ~ v2_struct_0(B)& m1_pre_topc(B,A)& ~ v2_struct_0(C)& m1_pre_topc(C,A) )=> k1_tsep_1(A,B,C) = k1_tsep_1(A,C,B) ) )).
fof(existence_m1_subset_1,axiom,(! [A] :? [B] : m1_subset_1(B,A) )).
fof(existence_l1_pre_topc,axiom,(? [A] : l1_pre_topc(A) )).
