fof(t28_waybel_7,conjecture,(! [A] :( ( v3_orders_2(A)& v4_orders_2(A)& v5_orders_2(A)& v2_waybel_1(A)& v1_lattice3(A)& v2_lattice3(A)& l1_orders_2(A) )=> ! [B] :( ( ~ v1_xboole_0(B)& v1_waybel_0(B,A)& v12_waybel_0(B,A)& m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A))) )=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ~ ( ~ r2_hidden(C,B)& ! [D] :( ( ~ v1_xboole_0(D)& v1_waybel_0(D,A)& v12_waybel_0(D,A)& m1_subset_1(D,k1_zfmisc_1(u1_struct_0(A))) )=> ~ ( v1_waybel_7(D,A)& r1_tarski(B,D)& ~ r2_hidden(C,D) ) ) ) ) ) ) )).
fof(reflexivity_r3_orders_2,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v3_orders_2(A)& l1_orders_2(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> r3_orders_2(A,B,B) ) )).
fof(t27_waybel_7,axiom,(! [A] :( ( v3_orders_2(A)& v4_orders_2(A)& v5_orders_2(A)& v2_waybel_1(A)& v1_lattice3(A)& v2_lattice3(A)& l1_orders_2(A) )=> ! [B] :( ( ~ v1_xboole_0(B)& v1_waybel_0(B,A)& v12_waybel_0(B,A)& m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A))) )=> ! [C] :( ( ~ v1_xboole_0(C)& v2_waybel_0(C,A)& v13_waybel_0(C,A)& m1_subset_1(C,k1_zfmisc_1(u1_struct_0(A))) )=> ~ ( r1_subset_1(B,C)& ! [D] :( ( ~ v1_xboole_0(D)& v1_waybel_0(D,A)& v12_waybel_0(D,A)& m1_subset_1(D,k1_zfmisc_1(u1_struct_0(A))) )=> ~ ( v1_waybel_7(D,A)& r1_tarski(B,D)& r1_subset_1(D,C) ) ) ) ) ) ) )).
fof(cc2_lattice3,axiom,(! [A] :( l1_orders_2(A)=> ( v2_lattice3(A)=> ~ v2_struct_0(A) ) ) )).
fof(d19_waybel_0,axiom,(! [A] :( l1_orders_2(A)=> ! [B] :( m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A)))=> ( v12_waybel_0(B,A)<=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( ( r2_hidden(C,B)& r1_orders_2(A,D,C) )=> r2_hidden(D,B) ) ) ) ) ) ) )).
fof(dt_k6_waybel_0,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& l1_orders_2(A)& m1_subset_1(B,u1_struct_0(A)) )=> m1_subset_1(k6_waybel_0(A,B),k1_zfmisc_1(u1_struct_0(A))) ) )).
fof(t18_waybel_0,axiom,(! [A] :( ( ~ v2_struct_0(A)& l1_orders_2(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ( r2_hidden(C,k6_waybel_0(A,B))<=> r1_orders_2(A,B,C) ) ) ) ) )).
fof(t3_xboole_0,axiom,(! [A,B] :( ~ ( ~ r1_xboole_0(A,B)& ! [C] :~ ( r2_hidden(C,A)& r2_hidden(C,B) ) )& ~ ( ? [C] :( r2_hidden(C,A)& r2_hidden(C,B) )& r1_xboole_0(A,B) ) ) )).
fof(redefinition_r1_subset_1,axiom,(! [A,B] :( ( ~ v1_xboole_0(A)& ~ v1_xboole_0(B) )=> ( r1_subset_1(A,B)<=> r1_xboole_0(A,B) ) ) )).
fof(fc13_waybel_0,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& v4_orders_2(A)& l1_orders_2(A)& m1_subset_1(B,u1_struct_0(A)) )=> v13_waybel_0(k6_waybel_0(A,B),A) ) )).
fof(t4_subset,axiom,(! [A,B,C] :( ( r2_hidden(A,B)& m1_subset_1(B,k1_zfmisc_1(C)) )=> m1_subset_1(A,C) ) )).
fof(redefinition_r3_orders_2,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v3_orders_2(A)& l1_orders_2(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> ( r3_orders_2(A,B,C)<=> r1_orders_2(A,B,C) ) ) )).
fof(fc9_waybel_0,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& v3_orders_2(A)& l1_orders_2(A)& m1_subset_1(B,u1_struct_0(A)) )=> ( ~ v1_xboole_0(k6_waybel_0(A,B))& v2_waybel_0(k6_waybel_0(A,B),A) ) ) )).
