fof(t17_waybel_7,conjecture,(! [A] :( ( v3_orders_2(A)& v4_orders_2(A)& v5_orders_2(A)& v1_lattice3(A)& v2_lattice3(A)& l1_orders_2(A) )=> ! [B] :( ( v3_orders_2(B)& v4_orders_2(B)& v5_orders_2(B)& v1_lattice3(B)& v2_lattice3(B)& l1_orders_2(B) )=> ( g1_orders_2(u1_struct_0(A),u1_orders_2(A)) = g1_orders_2(u1_struct_0(B),u1_orders_2(B))=> ! [C] :( ( ~ v1_xboole_0(C)& v1_waybel_0(C,A)& v12_waybel_0(C,A)& v1_waybel_7(C,A)& m1_subset_1(C,k1_zfmisc_1(u1_struct_0(A))) )=> ( ~ v1_xboole_0(C)& v1_waybel_0(C,B)& v12_waybel_0(C,B)& v1_waybel_7(C,B)& m1_subset_1(C,k1_zfmisc_1(u1_struct_0(B))) ) ) ) ) ) )).
fof(dt_l1_orders_2,axiom,(! [A] :( l1_orders_2(A)=> l1_struct_0(A) ) )).
fof(cc2_lattice3,axiom,(! [A] :( l1_orders_2(A)=> ( v2_lattice3(A)=> ~ v2_struct_0(A) ) ) )).
fof(d1_waybel_7,axiom,(! [A] :( ( v3_orders_2(A)& v4_orders_2(A)& v5_orders_2(A)& v2_lattice3(A)& l1_orders_2(A) )=> ! [B] :( ( ~ v1_xboole_0(B)& v1_waybel_0(B,A)& v12_waybel_0(B,A)& m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A))) )=> ( v1_waybel_7(B,A)<=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ~ ( r2_hidden(k12_lattice3(A,C,D),B)& ~ r2_hidden(C,B)& ~ r2_hidden(D,B) ) ) ) ) ) ) )).
fof(t27_yellow_0,axiom,(! [A] :( l1_orders_2(A)=> ! [B] :( l1_orders_2(B)=> ( g1_orders_2(u1_struct_0(A),u1_orders_2(A)) = g1_orders_2(u1_struct_0(B),u1_orders_2(B))=> ! [C] :( r2_yellow_0(A,C)=> k2_yellow_0(A,C) = k2_yellow_0(B,C) ) ) ) ) )).
fof(t21_yellow_0,axiom,(! [A] :( ( v5_orders_2(A)& l1_orders_2(A) )=> ( v2_lattice3(A)<=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> r2_yellow_0(A,k2_tarski(B,C)) ) ) ) ) )).
fof(t3_waybel_0,axiom,(! [A] :( l1_orders_2(A)=> ! [B] :( l1_orders_2(B)=> ( g1_orders_2(u1_struct_0(A),u1_orders_2(A)) = g1_orders_2(u1_struct_0(B),u1_orders_2(B))=> ! [C] :( m1_subset_1(C,k1_zfmisc_1(u1_struct_0(A)))=> ! [D] :( m1_subset_1(D,k1_zfmisc_1(u1_struct_0(B)))=> ( ( C = D& v1_waybel_0(C,A) )=> v1_waybel_0(D,B) ) ) ) ) ) ) )).
fof(dt_u1_orders_2,axiom,(! [A] :( l1_orders_2(A)=> m1_subset_1(u1_orders_2(A),k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A),u1_struct_0(A)))) ) )).
fof(t40_yellow_0,axiom,(! [A] :( ( v3_orders_2(A)& v4_orders_2(A)& v5_orders_2(A)& v2_lattice3(A)& l1_orders_2(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> k2_yellow_0(A,k7_domain_1(u1_struct_0(A),B,C)) = k12_lattice3(A,B,C) ) ) ) )).
fof(free_g1_orders_2,axiom,(! [A,B] :( m1_subset_1(B,k1_zfmisc_1(k2_zfmisc_1(A,A)))=> ! [C,D] :( g1_orders_2(A,B) = g1_orders_2(C,D)=> ( A = C& B = D ) ) ) )).
fof(commutativity_k2_tarski,axiom,(! [A,B] : k2_tarski(A,B) = k2_tarski(B,A) )).
fof(redefinition_k7_domain_1,axiom,(! [A,B,C] :( ( ~ v1_xboole_0(A)& m1_subset_1(B,A)& m1_subset_1(C,A) )=> k7_domain_1(A,B,C) = k2_tarski(B,C) ) )).
fof(t25_waybel_0,axiom,(! [A] :( l1_orders_2(A)=> ! [B] :( l1_orders_2(B)=> ( g1_orders_2(u1_struct_0(A),u1_orders_2(A)) = g1_orders_2(u1_struct_0(B),u1_orders_2(B))=> ! [C] :( m1_subset_1(C,k1_zfmisc_1(u1_struct_0(A)))=> ! [D] :( m1_subset_1(D,k1_zfmisc_1(u1_struct_0(B)))=> ( C = D=> ( ( v12_waybel_0(C,A)=> v12_waybel_0(D,B) )& ( v13_waybel_0(C,A)=> v13_waybel_0(D,B) ) ) ) ) ) ) ) ) )).
fof(fc2_struct_0,axiom,(! [A] :( ( ~ v2_struct_0(A)& l1_struct_0(A) )=> ~ v1_xboole_0(u1_struct_0(A)) ) )).
