fof(t52_lattices,conjecture,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ( k4_lattices(A,B,C) = k5_lattices(A)<=> r3_lattices(A,B,k7_lattices(A,C)) ) ) ) ) )).
fof(t27_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v7_lattices(A)& v8_lattices(A)& v9_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( r1_lattices(A,B,C)=> r1_lattices(A,k2_lattices(A,B,D),k2_lattices(A,C,D)) ) ) ) ) ) )).
fof(t47_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> k4_lattices(A,k7_lattices(A,B),B) = k5_lattices(A) ) ) )).
fof(t40_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v13_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> k4_lattices(A,k5_lattices(A),B) = k5_lattices(A) ) ) )).
fof(cc5_lattices,axiom,(! [A] :( l3_lattices(A)=> ( ( ~ v2_struct_0(A)& v17_lattices(A) )=> ( ~ v2_struct_0(A)& v11_lattices(A)& v15_lattices(A)& v16_lattices(A) ) ) ) )).
fof(dt_k7_lattices,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& l3_lattices(A)& m1_subset_1(B,u1_struct_0(A)) )=> m1_subset_1(k7_lattices(A,B),u1_struct_0(A)) ) )).
fof(d16_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& l1_lattices(A) )=> ( v13_lattices(A)=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ( B = k5_lattices(A)<=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ( k2_lattices(A,B,C) = B& k2_lattices(A,C,B) = B ) ) ) ) ) ) )).
fof(redefinition_r3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& v8_lattices(A)& v9_lattices(A)& l3_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> ( r3_lattices(A,B,C)<=> r1_lattices(A,B,C) ) ) )).
fof(dt_l3_lattices,axiom,(! [A] :( l3_lattices(A)=> ( l1_lattices(A)& l2_lattices(A) ) ) )).
fof(redefinition_k3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v4_lattices(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k3_lattices(A,B,C) = k1_lattices(A,B,C) ) )).
fof(redefinition_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k4_lattices(A,B,C) = k2_lattices(A,B,C) ) )).
fof(d3_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& l2_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ( r1_lattices(A,B,C)<=> k1_lattices(A,B,C) = C ) ) ) ) )).
fof(commutativity_k3_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v4_lattices(A)& l2_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k3_lattices(A,B,C) = k3_lattices(A,C,B) ) )).
fof(cc4_lattices,axiom,(! [A] :( l3_lattices(A)=> ( ( ~ v2_struct_0(A)& v15_lattices(A) )=> ( ~ v2_struct_0(A)& v13_lattices(A)& v14_lattices(A) ) ) ) )).
fof(cc1_lattices,axiom,(! [A] :( l3_lattices(A)=> ( ( ~ v2_struct_0(A)& v10_lattices(A) )=> ( ~ v2_struct_0(A)& v4_lattices(A)& v5_lattices(A)& v6_lattices(A)& v7_lattices(A)& v8_lattices(A)& v9_lattices(A) ) ) ) )).
fof(dt_k6_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& l2_lattices(A) )=> m1_subset_1(k6_lattices(A),u1_struct_0(A)) ) )).
fof(dt_k5_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& l1_lattices(A) )=> m1_subset_1(k5_lattices(A),u1_struct_0(A)) ) )).
fof(commutativity_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> k4_lattices(A,B,C) = k4_lattices(A,C,B) ) )).
fof(t31_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v11_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ! [D] :( m1_subset_1(D,u1_struct_0(A))=> k3_lattices(A,B,k4_lattices(A,C,D)) = k4_lattices(A,k3_lattices(A,B,C),k3_lattices(A,B,D)) ) ) ) ) )).
fof(d9_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& l3_lattices(A) )=> ( v9_lattices(A)<=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> k2_lattices(A,B,k1_lattices(A,B,C)) = B ) ) ) ) )).
fof(dt_k4_lattices,axiom,(! [A,B,C] :( ( ~ v2_struct_0(A)& v6_lattices(A)& l1_lattices(A)& m1_subset_1(B,u1_struct_0(A))& m1_subset_1(C,u1_struct_0(A)) )=> m1_subset_1(k4_lattices(A,B,C),u1_struct_0(A)) ) )).
fof(t21_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v8_lattices(A)& v9_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ( r1_lattices(A,B,C)<=> k2_lattices(A,B,C) = B ) ) ) ) )).
fof(t43_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v14_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> k4_lattices(A,k6_lattices(A),B) = B ) ) )).
fof(t49_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> k7_lattices(A,k7_lattices(A,B)) = B ) ) )).
fof(t50_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> k7_lattices(A,k4_lattices(A,B,C)) = k3_lattices(A,k7_lattices(A,B),k7_lattices(A,C)) ) ) ) )).
fof(t48_lattices,axiom,(! [A] :( ( ~ v2_struct_0(A)& v10_lattices(A)& v17_lattices(A)& l3_lattices(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> k3_lattices(A,k7_lattices(A,B),B) = k6_lattices(A) ) ) )).
