fof(t84_orders_2,conjecture,(! [A] :( ( ~ v2_struct_0(A)& v3_orders_2(A)& v4_orders_2(A)& v5_orders_2(A)& l1_orders_2(A) )=> ! [B] :( m1_orders_1(B,k1_orders_1(u1_struct_0(A)))=> ! [C] :( m2_orders_2(C,A,B)=> ! [D] :( m2_orders_2(D,A,B)=> ( r2_xboole_0(C,D)<=> m1_orders_2(C,A,D) ) ) ) ) ) )).
fof(dt_m2_orders_2,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& v3_orders_2(A)& v4_orders_2(A)& v5_orders_2(A)& l1_orders_2(A)& m1_orders_1(B,k1_orders_1(u1_struct_0(A))) )=> ! [C] :( m2_orders_2(C,A,B)=> ( v6_orders_2(C,A)& m1_subset_1(C,k1_zfmisc_1(u1_struct_0(A))) ) ) ) )).
fof(t57_xboole_1,axiom,(! [A,B] :~ ( r2_xboole_0(A,B)& r2_xboole_0(B,A) ) )).
fof(d2_orders_1,axiom,(! [A] : k1_orders_1(A) = k7_subset_1(k1_zfmisc_1(A),k9_setfam_1(A),k1_tarski(k1_xboole_0)) )).
fof(d16_orders_2,axiom,(! [A] :( ( ~ v2_struct_0(A)& v3_orders_2(A)& v4_orders_2(A)& v5_orders_2(A)& l1_orders_2(A) )=> ! [B] :( m1_orders_1(B,k1_orders_1(u1_struct_0(A)))=> ! [C] :( ( v6_orders_2(C,A)& m1_subset_1(C,k1_zfmisc_1(u1_struct_0(A))) )=> ( m2_orders_2(C,A,B)<=> ( C != k1_xboole_0& r2_wellord1(u1_orders_2(A),C)& ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( r2_hidden(D,C)=> k1_funct_1(B,k1_orders_2(A,k3_orders_2(A,C,D))) = D ) ) ) ) ) ) ) )).
fof(d8_xboole_0,axiom,(! [A,B] :( r2_xboole_0(A,B)<=> ( r1_tarski(A,B)& A != B ) ) )).
fof(t69_orders_2,axiom,(! [A] :( ( ~ v2_struct_0(A)& v3_orders_2(A)& v4_orders_2(A)& v5_orders_2(A)& l1_orders_2(A) )=> ! [B] :( m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A)))=> ! [C] :( m1_subset_1(C,k1_zfmisc_1(u1_struct_0(A)))=> ~ ( B != k1_xboole_0& m1_orders_2(B,A,C)& m1_orders_2(C,A,B) ) ) ) ) )).
fof(t59_xboole_1,axiom,(! [A,B,C] :( ( r1_tarski(A,B)& r2_xboole_0(B,C) )=> r2_xboole_0(A,C) ) )).
fof(t83_orders_2,axiom,(! [A] :( ( ~ v2_struct_0(A)& v3_orders_2(A)& v4_orders_2(A)& v5_orders_2(A)& l1_orders_2(A) )=> ! [B] :( m1_orders_1(B,k1_orders_1(u1_struct_0(A)))=> ! [C] :( m2_orders_2(C,A,B)=> ! [D] :( m2_orders_2(D,A,B)=> ( C != D=> ( m1_orders_2(C,A,D)<=> ~ m1_orders_2(D,A,C) ) ) ) ) ) ) )).
fof(t67_orders_2,axiom,(! [A] :( ( ~ v2_struct_0(A)& v3_orders_2(A)& v4_orders_2(A)& v5_orders_2(A)& l1_orders_2(A) )=> ! [B] :( m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A)))=> ! [C] :( m1_orders_2(C,A,B)=> r1_tarski(C,B) ) ) ) )).
