fof(t115_tmap_1,conjecture,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& m1_pre_topc(B,A) )=> ! [C] :( m1_pre_topc(C,k8_tmap_1(A,B))=> ( u1_struct_0(C) = u1_struct_0(B)=> ( v1_tsep_1(C,k8_tmap_1(A,B))& m1_pre_topc(C,k8_tmap_1(A,B)) ) ) ) ) ) )).
fof(abstractness_v1_pre_topc,axiom,(! [A] :( l1_pre_topc(A)=> ( v1_pre_topc(A)=> A = g1_pre_topc(u1_struct_0(A),u1_pre_topc(A)) ) ) )).
fof(d9_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A)))=> k6_tmap_1(A,B) = g1_pre_topc(u1_struct_0(A),k5_tmap_1(A,B)) ) ) )).
fof(dt_k8_tmap_1,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A)& m1_pre_topc(B,A) )=> ( v1_pre_topc(k8_tmap_1(A,B))& v2_pre_topc(k8_tmap_1(A,B))& l1_pre_topc(k8_tmap_1(A,B)) ) ) )).
fof(t104_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A)))=> ( u1_struct_0(k6_tmap_1(A,B)) = u1_struct_0(A)& u1_pre_topc(k6_tmap_1(A,B)) = k5_tmap_1(A,B) ) ) ) )).
fof(t105_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A)))=> ! [C] :( m1_subset_1(C,k1_zfmisc_1(u1_struct_0(k6_tmap_1(A,B))))=> ( C = B=> v3_pre_topc(C,k6_tmap_1(A,B)) ) ) ) ) )).
fof(t114_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& m1_pre_topc(B,A) )=> ( u1_struct_0(k8_tmap_1(A,B)) = u1_struct_0(A)& ! [C] :( m1_subset_1(C,k1_zfmisc_1(u1_struct_0(A)))=> ( C = u1_struct_0(B)=> u1_pre_topc(k8_tmap_1(A,B)) = k5_tmap_1(A,C) ) ) ) ) ) )).
fof(t16_tsep_1,axiom,(! [A] :( ( v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( m1_pre_topc(B,A)=> ! [C] :( m1_subset_1(C,k1_zfmisc_1(u1_struct_0(A)))=> ( C = u1_struct_0(B)=> ( ( v1_tsep_1(B,A)& m1_pre_topc(B,A) )<=> v3_pre_topc(C,A) ) ) ) ) ) )).
fof(t1_tsep_1,axiom,(! [A] :( l1_pre_topc(A)=> ! [B] :( m1_pre_topc(B,A)=> m1_subset_1(u1_struct_0(B),k1_zfmisc_1(u1_struct_0(A))) ) ) )).
fof(t35_borsuk_1,axiom,(! [A] :( l1_pre_topc(A)=> ! [B] :( m1_pre_topc(B,A)=> r1_tarski(u1_struct_0(B),u1_struct_0(A)) ) ) )).
fof(t3_subset,axiom,(! [A,B] :( m1_subset_1(A,k1_zfmisc_1(B))<=> r1_tarski(A,B) ) )).
