fof(t60_tmap_1,conjecture,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& v2_pre_topc(B)& l1_pre_topc(B) )=> ! [C] :( ( ~ v2_struct_0(C)& m1_pre_topc(C,B) )=> ! [D] :( ( v1_funct_1(D)& v1_funct_2(D,u1_struct_0(B),u1_struct_0(A))& m1_subset_1(D,k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(B),u1_struct_0(A)))) )=> ( g1_pre_topc(u1_struct_0(C),u1_pre_topc(C)) = g1_pre_topc(u1_struct_0(B),u1_pre_topc(B))=> r1_funct_2(u1_struct_0(B),u1_struct_0(A),u1_struct_0(C),u1_struct_0(A),D,k2_tmap_1(B,A,D,C)) ) ) ) ) ) )).
fof(d10_xboole_0,axiom,(! [A,B] :( A = B<=> ( r1_tarski(A,B)& r1_tarski(B,A) ) ) )).
fof(d4_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& v2_pre_topc(B)& l1_pre_topc(B) )=> ! [C] :( ( v1_funct_1(C)& v1_funct_2(C,u1_struct_0(A),u1_struct_0(B))& m1_subset_1(C,k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A),u1_struct_0(B)))) )=> ! [D] :( m1_pre_topc(D,A)=> k2_tmap_1(A,B,C,D) = k2_partfun1(u1_struct_0(A),u1_struct_0(B),C,u1_struct_0(D)) ) ) ) ) )).
fof(dt_k2_partfun1,axiom,(! [A,B,C,D] :( ( v1_funct_1(C)& m1_subset_1(C,k1_zfmisc_1(k2_zfmisc_1(A,B))) )=> ( v1_funct_1(k2_partfun1(A,B,C,D))& m1_subset_1(k2_partfun1(A,B,C,D),k1_zfmisc_1(k2_zfmisc_1(A,B))) ) ) )).
fof(dt_l1_pre_topc,axiom,(! [A] :( l1_pre_topc(A)=> l1_struct_0(A) ) )).
fof(dt_u1_pre_topc,axiom,(! [A] :( l1_pre_topc(A)=> m1_subset_1(u1_pre_topc(A),k1_zfmisc_1(k1_zfmisc_1(u1_struct_0(A)))) ) )).
fof(fc2_struct_0,axiom,(! [A] :( ( ~ v2_struct_0(A)& l1_struct_0(A) )=> ~ v1_xboole_0(u1_struct_0(A)) ) )).
fof(free_g1_pre_topc,axiom,(! [A,B] :( m1_subset_1(B,k1_zfmisc_1(k1_zfmisc_1(A)))=> ! [C,D] :( g1_pre_topc(A,B) = g1_pre_topc(C,D)=> ( A = C& B = D ) ) ) )).
fof(redefinition_k2_partfun1,axiom,(! [A,B,C,D] :( ( v1_funct_1(C)& m1_subset_1(C,k1_zfmisc_1(k2_zfmisc_1(A,B))) )=> k2_partfun1(A,B,C,D) = k7_relat_1(C,D) ) )).
fof(redefinition_r1_funct_2,axiom,(! [A,B,C,D,E,F] :( ( ~ v1_xboole_0(B)& ~ v1_xboole_0(D)& v1_funct_1(E)& v1_funct_2(E,A,B)& m1_subset_1(E,k1_zfmisc_1(k2_zfmisc_1(A,B)))& v1_funct_1(F)& v1_funct_2(F,C,D)& m1_subset_1(F,k1_zfmisc_1(k2_zfmisc_1(C,D))) )=> ( r1_funct_2(A,B,C,D,E,F)<=> E = F ) ) )).
fof(redefinition_r2_relset_1,axiom,(! [A,B,C,D] :( ( m1_subset_1(C,k1_zfmisc_1(k2_zfmisc_1(A,B)))& m1_subset_1(D,k1_zfmisc_1(k2_zfmisc_1(A,B))) )=> ( r2_relset_1(A,B,C,D)<=> C = D ) ) )).
fof(t2_tsep_1,axiom,(! [A] :( l1_pre_topc(A)=> m1_pre_topc(A,A) ) )).
fof(t40_funct_2,axiom,(! [A,B,C,D] :( ( v1_funct_1(D)& v1_funct_2(D,A,B)& m1_subset_1(D,k1_zfmisc_1(k2_zfmisc_1(A,B))) )=> ( r1_tarski(A,C)=> r2_relset_1(A,B,k2_partfun1(A,B,D,C),D) ) ) )).
