fof(t117_tmap_1,conjecture,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& m1_pre_topc(B,A) )=> r1_funct_2(u1_struct_0(A),u1_struct_0(k8_tmap_1(A,B)),u1_struct_0(A),u1_struct_0(A),k9_tmap_1(A,B),k3_struct_0(A)) ) ) )).
fof(d10_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A)))=> k7_tmap_1(A,B) = k6_partfun1(u1_struct_0(A)) ) ) )).
fof(d11_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( m1_pre_topc(B,A)=> ! [C] :( ( v1_pre_topc(C)& v2_pre_topc(C)& l1_pre_topc(C) )=> ( C = k8_tmap_1(A,B)<=> ! [D] :( m1_subset_1(D,k1_zfmisc_1(u1_struct_0(A)))=> ( D = u1_struct_0(B)=> C = k6_tmap_1(A,D) ) ) ) ) ) ) )).
fof(d12_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( m1_pre_topc(B,A)=> ! [C] :( ( v1_funct_1(C)& v1_funct_2(C,u1_struct_0(A),u1_struct_0(k8_tmap_1(A,B)))& m1_subset_1(C,k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A),u1_struct_0(k8_tmap_1(A,B))))) )=> ( C = k9_tmap_1(A,B)<=> ! [D] :( m1_subset_1(D,k1_zfmisc_1(u1_struct_0(A)))=> ( D = u1_struct_0(B)=> r1_funct_2(u1_struct_0(A),u1_struct_0(k8_tmap_1(A,B)),u1_struct_0(A),u1_struct_0(k6_tmap_1(A,D)),C,k7_tmap_1(A,D)) ) ) ) ) ) ) )).
fof(d4_struct_0,axiom,(! [A] :( l1_struct_0(A)=> k3_struct_0(A) = k6_partfun1(u1_struct_0(A)) ) )).
fof(dt_k8_tmap_1,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A)& m1_pre_topc(B,A) )=> ( v1_pre_topc(k8_tmap_1(A,B))& v2_pre_topc(k8_tmap_1(A,B))& l1_pre_topc(k8_tmap_1(A,B)) ) ) )).
fof(dt_k9_tmap_1,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A)& m1_pre_topc(B,A) )=> ( v1_funct_1(k9_tmap_1(A,B))& v1_funct_2(k9_tmap_1(A,B),u1_struct_0(A),u1_struct_0(k8_tmap_1(A,B)))& m1_subset_1(k9_tmap_1(A,B),k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A),u1_struct_0(k8_tmap_1(A,B))))) ) ) )).
fof(dt_l1_pre_topc,axiom,(! [A] :( l1_pre_topc(A)=> l1_struct_0(A) ) )).
fof(fc5_tmap_1,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A)& m1_pre_topc(B,A) )=> ( ~ v2_struct_0(k8_tmap_1(A,B))& v1_pre_topc(k8_tmap_1(A,B))& v2_pre_topc(k8_tmap_1(A,B)) ) ) )).
fof(t114_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& m1_pre_topc(B,A) )=> ( u1_struct_0(k8_tmap_1(A,B)) = u1_struct_0(A)& ! [C] :( m1_subset_1(C,k1_zfmisc_1(u1_struct_0(A)))=> ( C = u1_struct_0(B)=> u1_pre_topc(k8_tmap_1(A,B)) = k5_tmap_1(A,C) ) ) ) ) ) )).
fof(t1_tsep_1,axiom,(! [A] :( l1_pre_topc(A)=> ! [B] :( m1_pre_topc(B,A)=> m1_subset_1(u1_struct_0(B),k1_zfmisc_1(u1_struct_0(A))) ) ) )).
