fof(t116_tmap_1,conjecture,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& m1_pre_topc(B,A) )=> ( ( v1_tsep_1(B,A)& m1_pre_topc(B,A) )<=> g1_pre_topc(u1_struct_0(A),u1_pre_topc(A)) = k8_tmap_1(A,B) ) ) ) )).
fof(t103_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A)))=> ( r2_hidden(B,u1_pre_topc(A))<=> u1_pre_topc(A) = k5_tmap_1(A,B) ) ) ) )).
fof(fc6_pre_topc,axiom,(! [A] :( ( v2_pre_topc(A)& l1_pre_topc(A) )=> ( v1_pre_topc(g1_pre_topc(u1_struct_0(A),u1_pre_topc(A)))& v2_pre_topc(g1_pre_topc(u1_struct_0(A),u1_pre_topc(A))) ) ) )).
fof(t106_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A)))=> ( v3_pre_topc(B,A)<=> g1_pre_topc(u1_struct_0(A),u1_pre_topc(A)) = k6_tmap_1(A,B) ) ) ) )).
fof(t1_tsep_1,axiom,(! [A] :( l1_pre_topc(A)=> ! [B] :( m1_pre_topc(B,A)=> m1_subset_1(u1_struct_0(B),k1_zfmisc_1(u1_struct_0(A))) ) ) )).
fof(t2_tsep_1,axiom,(! [A] :( l1_pre_topc(A)=> m1_pre_topc(A,A) ) )).
fof(dt_m1_pre_topc,axiom,(! [A] :( l1_pre_topc(A)=> ! [B] :( m1_pre_topc(B,A)=> l1_pre_topc(B) ) ) )).
fof(t7_tsep_1,axiom,(! [A] :( ( v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( m1_pre_topc(B,A)=> ! [C] :( m1_pre_topc(C,B)=> m1_pre_topc(C,A) ) ) ) )).
fof(abstractness_v1_pre_topc,axiom,(! [A] :( l1_pre_topc(A)=> ( v1_pre_topc(A)=> A = g1_pre_topc(u1_struct_0(A),u1_pre_topc(A)) ) ) )).
fof(t104_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A)))=> ( u1_struct_0(k6_tmap_1(A,B)) = u1_struct_0(A)& u1_pre_topc(k6_tmap_1(A,B)) = k5_tmap_1(A,B) ) ) ) )).
fof(d1_pre_topc,axiom,(! [A] :( l1_pre_topc(A)=> ( v2_pre_topc(A)<=> ( r2_hidden(u1_struct_0(A),u1_pre_topc(A))& ! [B] :( m1_subset_1(B,k1_zfmisc_1(k1_zfmisc_1(u1_struct_0(A))))=> ( r1_tarski(B,u1_pre_topc(A))=> r2_hidden(k5_setfam_1(u1_struct_0(A),B),u1_pre_topc(A)) ) )& ! [B] :( m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A)))=> ! [C] :( m1_subset_1(C,k1_zfmisc_1(u1_struct_0(A)))=> ( ( r2_hidden(B,u1_pre_topc(A))& r2_hidden(C,u1_pre_topc(A)) )=> r2_hidden(k9_subset_1(u1_struct_0(A),B,C),u1_pre_topc(A)) ) ) ) ) ) ) )).
fof(dt_k8_tmap_1,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A)& m1_pre_topc(B,A) )=> ( v1_pre_topc(k8_tmap_1(A,B))& v2_pre_topc(k8_tmap_1(A,B))& l1_pre_topc(k8_tmap_1(A,B)) ) ) )).
fof(rc1_connsp_1,axiom,(! [A] :( l1_pre_topc(A)=> ? [B] :( m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A)))& v1_xboole_0(B) ) ) )).
fof(t35_borsuk_1,axiom,(! [A] :( l1_pre_topc(A)=> ! [B] :( m1_pre_topc(B,A)=> r1_tarski(u1_struct_0(B),u1_struct_0(A)) ) ) )).
fof(d1_tsep_1,axiom,(! [A] :( l1_pre_topc(A)=> ! [B] :( m1_pre_topc(B,A)=> ( v1_tsep_1(B,A)<=> ! [C] :( m1_subset_1(C,k1_zfmisc_1(u1_struct_0(A)))=> ( C = u1_struct_0(B)=> v3_pre_topc(C,A) ) ) ) ) ) )).
fof(dt_k6_tmap_1,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A)& m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A))) )=> ( v1_pre_topc(k6_tmap_1(A,B))& v2_pre_topc(k6_tmap_1(A,B))& l1_pre_topc(k6_tmap_1(A,B)) ) ) )).
fof(t60_pre_topc,axiom,(! [A] :( ( v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( v3_pre_topc(B,A)& m1_subset_1(B,k1_zfmisc_1(u1_struct_0(A))) )<=> ( v3_pre_topc(B,g1_pre_topc(u1_struct_0(A),u1_pre_topc(A)))& m1_subset_1(B,k1_zfmisc_1(u1_struct_0(g1_pre_topc(u1_struct_0(A),u1_pre_topc(A))))) ) ) ) )).
fof(t6_boole,axiom,(! [A] :( v1_xboole_0(A)=> A = k1_xboole_0 ) )).
fof(t114_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& m1_pre_topc(B,A) )=> ( u1_struct_0(k8_tmap_1(A,B)) = u1_struct_0(A)& ! [C] :( m1_subset_1(C,k1_zfmisc_1(u1_struct_0(A)))=> ( C = u1_struct_0(B)=> u1_pre_topc(k8_tmap_1(A,B)) = k5_tmap_1(A,C) ) ) ) ) ) )).
fof(t5_pre_topc,axiom,(! [A] :( ( v2_pre_topc(A)& l1_pre_topc(A) )=> r2_hidden(k1_xboole_0,u1_pre_topc(A)) ) )).
fof(t115_tmap_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( ( ~ v2_struct_0(B)& m1_pre_topc(B,A) )=> ! [C] :( m1_pre_topc(C,k8_tmap_1(A,B))=> ( u1_struct_0(C) = u1_struct_0(B)=> ( v1_tsep_1(C,k8_tmap_1(A,B))& m1_pre_topc(C,k8_tmap_1(A,B)) ) ) ) ) ) )).
fof(t11_tmap_1,axiom,(! [A] :( l1_pre_topc(A)=> ! [B] :( m1_pre_topc(B,A)=> ( v1_pre_topc(g1_pre_topc(u1_struct_0(B),u1_pre_topc(B)))& m1_pre_topc(g1_pre_topc(u1_struct_0(B),u1_pre_topc(B)),A) ) ) ) )).
fof(t4_tsep_1,axiom,(! [A] :( ( v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( m1_pre_topc(B,A)=> ! [C] :( m1_pre_topc(C,A)=> ( r1_tarski(u1_struct_0(B),u1_struct_0(C))<=> m1_pre_topc(B,C) ) ) ) ) )).
