fof(t27_waybel_9,conjecture,(! [A] :( ( v2_pre_topc(A)& v8_pre_topc(A)& v3_orders_2(A)& v4_orders_2(A)& v5_orders_2(A)& v1_lattice3(A)& v2_lattice3(A)& l1_waybel_9(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ( ! [C] :( m1_subset_1(C,u1_struct_0(A))=> v5_pre_topc(k4_waybel_1(A,C),A,A) )=> v4_pre_topc(k6_waybel_0(A,B),A) ) ) ) )).
fof(d12_pre_topc,axiom,(! [A] :( l1_pre_topc(A)=> ! [B] :( l1_pre_topc(B)=> ! [C] :( ( v1_funct_1(C)& v1_funct_2(C,u1_struct_0(A),u1_struct_0(B))& m1_subset_1(C,k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A),u1_struct_0(B)))) )=> ( v5_pre_topc(C,A,B)<=> ! [D] :( m1_subset_1(D,k1_zfmisc_1(u1_struct_0(B)))=> ( v4_pre_topc(D,B)=> v4_pre_topc(k8_relset_1(u1_struct_0(A),u1_struct_0(B),C,D),A) ) ) ) ) ) ) )).
fof(dt_k4_waybel_1,axiom,(! [A,B] :( ( ~ v2_struct_0(A)& l1_orders_2(A)& m1_subset_1(B,u1_struct_0(A)) )=> ( v1_funct_1(k4_waybel_1(A,B))& v1_funct_2(k4_waybel_1(A,B),u1_struct_0(A),u1_struct_0(A))& m1_subset_1(k4_waybel_1(A,B),k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A),u1_struct_0(A)))) ) ) )).
fof(cc1_lattice3,axiom,(! [A] :( l1_orders_2(A)=> ( v1_lattice3(A)=> ~ v2_struct_0(A) ) ) )).
fof(t7_waybel_9,axiom,(! [A] :( ( v3_orders_2(A)& v5_orders_2(A)& v2_lattice3(A)& l1_orders_2(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> k8_relset_1(u1_struct_0(A),u1_struct_0(A),k4_waybel_1(A,B),k6_domain_1(u1_struct_0(A),B)) = k6_waybel_0(A,B) ) ) )).
fof(t10_pcomps_1,axiom,(! [A] :( ( ~ v2_struct_0(A)& v2_pre_topc(A)& l1_pre_topc(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ( v8_pre_topc(A)=> v4_pre_topc(k6_domain_1(u1_struct_0(A),B),A) ) ) ) )).
fof(dt_k7_relset_1,axiom,(! [A,B,C,D] :( m1_subset_1(C,k1_zfmisc_1(k2_zfmisc_1(A,B)))=> m1_subset_1(k7_relset_1(A,B,C,D),k1_zfmisc_1(B)) ) )).
fof(dt_l1_waybel_9,axiom,(! [A] :( l1_waybel_9(A)=> ( l1_pre_topc(A)& l1_orders_2(A) ) ) )).
fof(t6_waybel_9,axiom,(! [A] :( ( v3_orders_2(A)& v5_orders_2(A)& v2_lattice3(A)& l1_orders_2(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> k7_relset_1(u1_struct_0(A),u1_struct_0(A),k4_waybel_1(A,B),k6_waybel_0(A,B)) = k6_domain_1(u1_struct_0(A),B) ) ) )).
