fof(t32_yellow_0,conjecture,(! [A] :( ( ~ v2_struct_0(A)& v5_orders_2(A)& v3_lattice3(A)& l1_orders_2(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( B = k1_yellow_0(A,C)<=> ( r2_lattice3(A,C,B)& ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( r2_lattice3(A,C,D)=> r1_orders_2(A,B,D) ) ) ) ) ) ) )).
fof(t9_yellow_0,axiom,(! [A] :( l1_orders_2(A)=> ! [B,C] :( r1_tarski(B,C)=> ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( ( r1_lattice3(A,C,D)=> r1_lattice3(A,B,D) )& ( r2_lattice3(A,C,D)=> r2_lattice3(A,B,D) ) ) ) ) ) )).
fof(t5_yellow_0,axiom,(! [A] :( ( ~ v2_struct_0(A)& l1_orders_2(A) )=> ! [B,C] :( m1_subset_1(C,u1_struct_0(A))=> ( ( r2_lattice3(A,B,C)=> r2_lattice3(A,k3_xboole_0(B,u1_struct_0(A)),C) )& ( r2_lattice3(A,k3_xboole_0(B,u1_struct_0(A)),C)=> r2_lattice3(A,B,C) )& ( r1_lattice3(A,B,C)=> r1_lattice3(A,k3_xboole_0(B,u1_struct_0(A)),C) )& ( r1_lattice3(A,k3_xboole_0(B,u1_struct_0(A)),C)=> r1_lattice3(A,B,C) ) ) ) ) )).
fof(t25_orders_2,axiom,(! [A] :( ( v5_orders_2(A)& l1_orders_2(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( m1_subset_1(C,u1_struct_0(A))=> ( ( r1_orders_2(A,B,C)& r1_orders_2(A,C,B) )=> B = C ) ) ) ) )).
fof(d9_yellow_0,axiom,(! [A] :( l1_orders_2(A)=> ! [B,C] :( m1_subset_1(C,u1_struct_0(A))=> ( r1_yellow_0(A,B)=> ( C = k1_yellow_0(A,B)<=> ( r2_lattice3(A,B,C)& ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( r2_lattice3(A,B,D)=> r1_orders_2(A,C,D) ) ) ) ) ) ) ) )).
fof(t17_xboole_1,axiom,(! [A,B] : r1_tarski(k3_xboole_0(A,B),A) )).
fof(t30_yellow_0,axiom,(! [A] :( ( v5_orders_2(A)& l1_orders_2(A) )=> ! [B] :( m1_subset_1(B,u1_struct_0(A))=> ! [C] :( ( ( B = k1_yellow_0(A,C)& r1_yellow_0(A,C) )=> ( r2_lattice3(A,C,B)& ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( r2_lattice3(A,C,D)=> r1_orders_2(A,B,D) ) ) ) )& ( ( r2_lattice3(A,C,B)& ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( r2_lattice3(A,C,D)=> r1_orders_2(A,B,D) ) ) )=> ( B = k1_yellow_0(A,C)& r1_yellow_0(A,C) ) ) ) ) ) )).
fof(dt_k1_yellow_0,axiom,(! [A,B] :( l1_orders_2(A)=> m1_subset_1(k1_yellow_0(A,B),u1_struct_0(A)) ) )).
fof(commutativity_k3_xboole_0,axiom,(! [A,B] : k3_xboole_0(A,B) = k3_xboole_0(B,A) )).
fof(t15_yellow_0,axiom,(! [A] :( ( v5_orders_2(A)& l1_orders_2(A) )=> ! [B] :( r1_yellow_0(A,B)<=> ? [C] :( m1_subset_1(C,u1_struct_0(A))& r2_lattice3(A,B,C)& ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( r2_lattice3(A,B,D)=> r1_orders_2(A,C,D) ) ) ) ) ) )).
fof(d12_lattice3,axiom,(! [A] :( l1_orders_2(A)=> ( v3_lattice3(A)<=> ! [B] :? [C] :( m1_subset_1(C,u1_struct_0(A))& r2_lattice3(A,B,C)& ! [D] :( m1_subset_1(D,u1_struct_0(A))=> ( r2_lattice3(A,B,D)=> r1_orders_2(A,C,D) ) ) ) ) ) )).
